// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk_BjAMa-ZqeNTfUAIQvNrw5xutnIet7Y',
    appId: '1:952217268448:web:1ec5e07e969c6d9eb76085',
    messagingSenderId: '952217268448',
    projectId: 'e-pesantrensantri',
    authDomain: 'e-pesantrensantri.firebaseapp.com',
    storageBucket: 'e-pesantrensantri.firebasestorage.app',
    measurementId: 'G-498H3Z83SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5tEczFDSf4UsZ0mi8iYASttdMGsdRrk',
    appId: '1:952217268448:android:dfc6fd8b674b8f82b76085',
    messagingSenderId: '952217268448',
    projectId: 'e-pesantrensantri',
    storageBucket: 'e-pesantrensantri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66g-GyvlDctpDMGJCQu-J9xWKVQinhAY',
    appId: '1:952217268448:ios:c8aeedcf19b3c540b76085',
    messagingSenderId: '952217268448',
    projectId: 'e-pesantrensantri',
    storageBucket: 'e-pesantrensantri.firebasestorage.app',
    iosBundleId: 'com.pesantren.ePenilaianSantri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66g-GyvlDctpDMGJCQu-J9xWKVQinhAY',
    appId: '1:952217268448:ios:c8aeedcf19b3c540b76085',
    messagingSenderId: '952217268448',
    projectId: 'e-pesantrensantri',
    storageBucket: 'e-pesantrensantri.firebasestorage.app',
    iosBundleId: 'com.pesantren.ePenilaianSantri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk_BjAMa-ZqeNTfUAIQvNrw5xutnIet7Y',
    appId: '1:952217268448:web:9d8cd1764a11bda3b76085',
    messagingSenderId: '952217268448',
    projectId: 'e-pesantrensantri',
    authDomain: 'e-pesantrensantri.firebaseapp.com',
    storageBucket: 'e-pesantrensantri.firebasestorage.app',
    measurementId: 'G-PK8P2YN357',
  );
}
